# Generated by Django 4.1.7 on 2023-04-24 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profesor", "0001_initial"),
        ("alumno", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Materia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                (
                    "alumnos",
                    models.ManyToManyField(related_name="materias", to="alumno.alumno"),
                ),
                (
                    "profesor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profesor.profesor",
                    ),
                ),
            ],
        ),
    ]
