# Generated by Django 4.1.7 on 2023-05-22 20:50

import apps.utils.func_time
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alumno", "0001_initial"),
        ("profesor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Materia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                (
                    "alumnos",
                    models.ManyToManyField(related_name="materias", to="alumno.alumno"),
                ),
                (
                    "profesor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profesor.profesor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MateriaAlumno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=apps.utils.func_time.comienzo_materia, null=True
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        default=apps.utils.func_time.fin_materia, null=True
                    ),
                ),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="alumno.alumno"
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materia.materia",
                    ),
                ),
            ],
            managers=[("objects_all", django.db.models.manager.Manager()),],
        ),
    ]
