# Generated by Django 4.2 on 2023-04-26 00:02

import apps.utils.func_time
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0002_alumno_monotributo'),
        ('materia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=apps.utils.func_time.comienzo_materia, null=True)),
                ('end_date', models.DateField(default=apps.utils.func_time.fin_materia, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.alumno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.materia')),
            ],
            managers=[
                ('objects_all', django.db.models.manager.Manager()),
            ],
        ),
    ]
