# Generated by Django 4.1.7 on 2023-05-22 20:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("materia", "0001_initial"),
        ("profesor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Examen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(default=datetime.datetime.now)),
                ("titulo", models.CharField(default="", max_length=50)),
                ("descripcion", models.TextField(default="")),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materia.materia",
                    ),
                ),
                (
                    "profesor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profesor.profesor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContenidoExamen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=50)),
                ("descripcion", models.TextField()),
                ("respuesta", models.TextField()),
                ("puntaje", models.IntegerField()),
                (
                    "examen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="examen.examen"
                    ),
                ),
            ],
        ),
    ]
