# Generated by Django 4.1.7 on 2023-04-24 21:03

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("dni", models.IntegerField()),
                ("fecha_nacimiento", models.DateField()),
                ("email", models.EmailField(max_length=254)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={"abstract": False,},
            managers=[("objects_all", django.db.models.manager.Manager()),],
        ),
    ]
