# Generated by Django 4.2 on 2023-04-26 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='fecha_alta',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
