# Generated by Django 4.2 on 2023-04-26 00:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='monotributo',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
