# Generated by Django 4.1.7 on 2023-05-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumno", "0003_alumno_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumno",
            name="apellido",
            field=models.CharField(max_length=50, verbose_name="Apellidirigillio"),
        ),
    ]
